### ISSUE TITLE
Issues getting chained properties

### ISSUE THREAD

**Issue by narkeeso** [Dani723/ember-validation#1]
Hello @Dani723,

I am a fan of the simplicity of your validation library and have been using it with no issue until I came across setting properties that are chained such as 'company.name' which is a belongsTo relationship.

Is this a bug or am I doing something wrong?

``` javascript
App.CompanyController = Em.ObjectController.extend({
    validate: function() {
        var validator = Em.Validation.map(function() {
            this.property("company.name", "Company Name").required();
        });

        var result = validator.validate(form);
        result.get('company.name'); // returns undefined
        result.get('company'); // returns an object
    }
});
```

However, this method works but would prefer the former... notice I am getting 'company' at validate():

``` javascript
App.CompanyController = Em.ObjectController.extend({
    validate: function() {
        var validator = Em.Validation.map(function() {
            this.property("name", "Company Name").required();
        });

        var result = validator.validate(form.get('company');
        result.get('name'); // returns object
    }
});
```

Thanks for the excellent library.

**Comment by Dani723** [comment]
Hi @narkeeso,

first of all thanks for using Ember Validation and reporting this issue.
The problem lies within the handling of the properties in the ValidationResult class.

The result for each property is stored in a key-value container with the name of the property as the key.
In your case 'company.name'. To allow access via result.get('company.name'), the unknownProperty-method of Ember is used.

Unfortunately that doesn't work for chained properties as it splits up the property name. 

I've commited a fix. Please let me know if this works for you.

I'm not fully satisfied with this solution and will probably rewrite the ValidationResult class in the next days.

**Comment by narkeeso** [comment]
@Dani723 - Thank you for the quick fix! It works great!

The reason I am doing it this way is because I am building a form wizard that has model properties spread out amongst several pages so cherry picking my validations is ideal in this case. Your library so far works the best for this use case. I also like that the validations are chained and will not output an array of messages unlike other libraries. It's very well thought out, lightweight, and easy to learn.

**Comment by narkeeso** [comment]
After more extensive use, I've found that passing in the required properties via model.validate(properties) is much cleaner and keeps the validations DRY and attached to my object model:

``` javascript
// Controller
App.CompanyController = Em.ObjectController.extend({
    needs: "onboarding",
    form: null,
    formBinding: "controllers.onboarding",

    save: function() {
        var form = this.get('form');
        var formModel = form.get('model');

        var validateProperties = ['first_name', 'last_name', 'phone', 'password', 'email_address', 'company.name', 'company.name'];
        var result = formModel.validate(validateProperties);
        form.set('errors', result);

        ...
    }
});

// Model
App.Form = Em.Model.extend(Em.Validation.ValidatorSupport, {
    'id': attr(),
    'first_name': attr(),
    'last_name': attr(),
    'password': attr(),
    'phone': attr(),
    'email_address': attr(),
    'company': Em.belongsTo('App.Company', { key: 'company', embedded: true }),

    validator: Em.Validation.map(function() {
        this.property("first_name", "First Name").required();
        this.property("last_name", "Last Name").required();
        this.property("password", "Password").required().minLength(6).maxLength(64).badPassword();
        this.property("phone").required();
        this.property("email_address", "E-mail").required().mail();
    })
});

App.Company = Em.Model.extend(Em.Validation.ValidatorSupport, {
    'id': attr(),
    'name': attr(),
    'phone': attr(),
    'address': Em.belongsTo('App.Address', { key: 'address', embedded: true }),
    'restaurants': Em.hasMany('App.Restaurant', { key: 'restaurants', embedded: true }),

    validator: Em.Validation.map(function() {
        this.property("name", "Company Name").required();
        this.property("phone", "Company Phone").required();
    })
});
```

However, calling chained properties via this method is not working as well (company.name, company.phone). Passing properties as singles works fine.

For now I will use the method you patched for me but thought you should know. Unless I am using the validate() function incorrectly.

**Comment by Dani723** [comment]
The validator of the form doesn't know about the validator of the the company and its properties. Unfortunately, that won't work at the moment.

As mentioned above, I'm not really happy with the current handling of the chained properties/nested resources. 
Currently I'm working on the following approach:

``` javascript

App.Form = Em.Model.extend(Em.Validation.ValidatorSupport, {
    ...
    validator: Em.Validation.map(function() {
        this.property("first_name", "First Name").required();
        this.property("last_name", "Last Name").required();
        this.property("password", "Password").required().minLength(6).maxLength(64).badPassword();
        this.property("phone").required();
        this.property("email_address", "E-mail").required().mail();
        // company is an object with its own validator
        this.nested("company", Em.Validation.map(function() {
            this.property("name", "Company Name").required();
            this.property("phone", "Company Phone").required();
        }));
    })
});

```

or with seperated classes

``` javascript

App.Company = Em.Model.extend(Em.Validation.ValidatorSupport, {
    ...
    validator: Em.Validation.map(function() {
        this.property("name", "Company Name").required();
        this.property("phone", "Company Phone").required();
    })
});

App.Form = Em.Model.extend(Em.Validation.ValidatorSupport, {
    ...
    validator: Em.Validation.map(function() {
        this.property("first_name", "First Name").required();
        this.property("last_name", "Last Name").required();
        this.property("password", "Password").required().minLength(6).maxLength(64).badPassword();
        this.property("phone").required();
        this.property("email_address", "E-mail").required().mail();
        this.nested("company", App.Company); // reuses the Company's validator
    })
});
```
