### ISSUE TITLE
Required fields with value 0

### ISSUE THREAD

**Issue by AshesOfOwls** [Dani723/ember-validation#2]
Hey there, thanks for the great library.

Currently I have a field that is .required().number() validated. The issue is that if the field is prepopulated with the number 0 then it fails on the RequiredRule validation. It will however correctly validate as long as the field was modified (even if replacing the 0 with another 0).

The quick fix that I did on my copy was to do this:

``` javascript
Ember.Validation.RequiredRule = Ember.Validation.BaseRule.extend({

  message: msgs.required,
  override: false,

  validate: function(value, required) {
    if(value != 0) {
      return !value ? !required : true;
    } else {
      return true;
    }
  },

  override: function(value, isValid, required) {
    return !value && !required;
  }

});
```

But that is just a hotfix that will probably break some other use cases.

**Comment by Dani723** [comment]
Hi,

first of all, thanks for using EV.

You're right. The RequiredRule's validate() is too simplistic.
This problem also effects 'NaN' or 'false'.

In my understanding the required() should succeed on any kind of value 
besides null or an empty string.

Maybe this is the right approach:

Ember.Validation.RequiredRule = Ember.Validation.BaseRule.extend({

   message: msgs.required,

   isEmpty: function(value) {
     return value === null || value === '';
   },

   validate: function(value, required) {
     return  this.isEmpty(value) ? !required : true;
   },

   override: function(value, isValid, required) {
     return this.isEmpty(value) && !required;
   }

});

Greets
Dani

**Comment by AshesOfOwls** [comment]
Works great on my end!
